[16.0][FIX] currency_rate_update
OCA/currency pull request #159
Opened 2022-12-26 03:00 UTC by kanda999

Current behavior:
https://github.com/OCA/currency/pull/153　With this update, If there are days with no data then the rate updates will get stuck.  Get the data, otherwise scheduled_date will not be updated to avoid lost data.
Therefore, you cannot use a provider that does not update data on weekends.

This comment shows that the weekend update with no data was considered in V13.
https://github.com/OCA/currency/pull/147#issuecomment-1346322636

But when there is no data, the method provider._schedule_next_run() has been erased in V16 and backport this update.
https://github.com/OCA/currency/pull/153#discussion_r1055358952

I created a Boolean field in provider to be able to use providers with no data on weekends with this update.

2022-12-26 07:22 UTC, yostashiro requested changes
Please add tests as well.

2022-12-26 07:22 UTC, yostashiro commented on currency_rate_update/models/res_currency_rate_provider.py
> +    no_data_skip = fields.Boolean(default=False)
```suggestion
    force_update_next_run = fields.Boolean(
        "Force Update Next Scheduled Update",
        help="Update 'Next scheduled update' to today even when where is no rate data received from the provider in the update process. Select this if the provider does not provide the rate data for certain days (e.g. public holidays)."
    )
```

2022-12-26 07:22 UTC, yostashiro commented on currency_rate_update/models/res_currency_rate_provider.py
> +                    provider._schedule_next_run()
```suggestion
                if provider.force_update_next_run:
                    provider.next_run = fields.Date.context_today(self)
```

We should not go as far as running _schedule_next_run() if there is no data.  We should just update next_run to today.

2022-12-26 07:22 UTC, yostashiro commented on currency_rate_update/models/res_currency_rate_provider.py
> +
```suggestion
```

2022-12-26 07:22 UTC, yostashiro commented on currency_rate_update/views/res_currency_rate_provider.xml
> +                <field name="no_data_skip" />
```suggestion
                <field name="force_update_next_run" optional="hide" />
```

2022-12-26 07:22 UTC, yostashiro commented on currency_rate_update/views/res_currency_rate_provider.xml
> +                            <field name="no_data_skip" />
```suggestion
                            <field name="force_update_next_run" />
```

2022-12-26 07:26 UTC, yostashiro commented
@kanda999 We may also change the tag from 'FIX' to 'IMP' as the issue may not necessarily be a bug.

2022-12-26 21:51 UTC, pedrobaeza commented
Why do you need this? European Bank provider, which is the one we use, doesn't update rates on weekends, so current behavior has been though with it in mind.

2022-12-28 06:05 UTC, kanda999 commented
@pedrobaeza 
European Bank provider will be stuck at the weekend with current behavior.
You can see that from the test code.
https://github.com/OCA/currency/blob/fbc243cb8a85ffcba5f50d1893fc6c55cdc4bc28/currency_rate_update/tests/test_currency_rate_update.py#L154-L161
In this test
The `next_run` set to Next run : 2019-07-06 is still Next run 2019-07-06 when we run cron. This means it is stuck on the weekend.

So I create integer fields and user can set number of retries in case of no data.

2022-12-28 06:39 UTC, yostashiro requested changes
In an attempt to make the concept a bit easier to understand...

2022-12-28 06:39 UTC, yostashiro commented on currency_rate_update/models/res_currency_rate_provider.py
> +    no_data_occurrence = fields.Integer(readonly=True)
```suggestion
    retry = fields.Integer("Current Try", readonly=True, help="Number of update attempts done by scheduler for the Next Scheduled Update date.")
    max_retry = fields.Integer("Max Retries", help="Maximum number of update attempts for the Next Scheduled Update date. An attempt that goes over this number will update the Next Scheduled Update date to today.")
```

2022-12-28 06:39 UTC, yostashiro commented on currency_rate_update/models/res_currency_rate_provider.py
> +                    provider.no_data_occurrence = 0
```suggestion
                if is_sheduled and provider.retry > provider.max_retry:
                    provider.next_run = fields.Date.context_today(self)
                    provider.retry = 0
```

Add the following at the beginning of the loop:

```
if is_scheduled:
    provider.retry += 1
```

2022-12-28 06:39 UTC, yostashiro commented on currency_rate_update/models/res_currency_rate_provider.py
> +            provider.no_data_occurrence = 0
```suggestion
```

Add `provider.retry = 0` to the end of `_schedule_next_run()`.

2022-12-28 06:39 UTC, yostashiro commented on currency_rate_update/views/res_currency_rate_provider.xml
> +                            <field name="allow_no_data_occurrence" />
```suggestion
                            <div>
                                <label for="retry" string="Current Try / Max Retries"/>
                                <field name="retry" class="oe_inline"/> /
                                <field name="max_retry" class="oe_inline"/>
                            </div>
```

2022-12-28 07:11 UTC, pedrobaeza commented
> The next_run set to Next run : 2019-07-06 is still Next run 2019-07-06 when we run cron. This means it is stuck on the weekend.

But that's the idea. On Monday, it will try to fetch Saturday, Sunday and Monday, and being able to fetch Monday's data, then `next_run` will be changed to Monday.

Why is this? Because with the previous code, if the cron in programmed on Monday, but before Monday data is available, you will lose such rate and not being able to get it again.

So I think you shouldn't reintroduce the old behavior.

2022-12-28 07:51 UTC, kanda999 commented
@pedrobaeza 
Please see:
https://github.com/OCA/currency/blob/fbc243cb8a85ffcba5f50d1893fc6c55cdc4bc28/currency_rate_update/models/res_currency_rate_provider.py#L281-L282

In the current code, the range to fetch data is up to the date of `next_run`. (`date_to = provider.next_run`)　So if `next_run` is set to Saturday, and the cron runs on Monday, it will not be able to fetch Monday's data and this update stacks.

So we need to improve how many retries we can do like my PR, or change the range of data it can fetch.

2022-12-28 07:54 UTC, pedrobaeza commented
I was asking the same in https://github.com/OCA/currency/pull/147#issuecomment-1352700663 and @victoralmau (he's on holidays now) told me that it iterates.

2022-12-28 08:07 UTC, kanda999 commented
> I was asking the same in [#147 (comment)](https://github.com/OCA/currency/pull/147#issuecomment-1352700663) and @victoralmau (he's on holidays now) told me that it iterates.

Yes, I see that comment.  But now it can not iterate.  I think it's because the logic has changed in https://github.com/OCA/currency/pull/153

2022-12-28 08:10 UTC, pedrobaeza commented
But the patch should be then to iterate from next_run to today, not to restore the old behavior.

2022-12-28 08:23 UTC, yostashiro commented
@pedrobaeza In that case, do you suggest that `newest_only=True` should be removed from the following line?
https://github.com/OCA/currency/blob/fbc243cb8a85ffcba5f50d1893fc6c55cdc4bc28/currency_rate_update/models/res_currency_rate_provider.py#L282

If you somehow fail to fetch the rate of Monday and today is Tuesday, then you will not get the rate of Monday (you will only get the rate of Tuesday), otherwise.

2022-12-28 09:01 UTC, pedrobaeza commented
But why adding a new parameter. The system should fetch the remaining dates from `next_run` to today, and set `next_run` on the last day that fetches data. If that's not the behavior, then let's fix it, but not to complicate it with further parameters.

2022-12-28 09:44 UTC, yostashiro commented
> But why adding a new parameter.

Because we got lost in translation in this update https://github.com/OCA/currency/pull/153. :sweat_smile:

> The system should fetch the remaining dates from `next_run` to today, and set `next_run` on the last day that fetches data. If that's not the behavior, then let's fix it, but not to complicate it with further parameters.

OK, I'd suggest that we change the following part
https://github.com/OCA/currency/blob/fbc243cb8a85ffcba5f50d1893fc6c55cdc4bc28/currency_rate_update/models/res_currency_rate_provider.py#L281-L282
to
```python
                newest_only = False
                date_to = provider.next_run
                if provider.interval_type == "days" and provider.interval_type == 1:
                    newest_only = True
                    date_to = fields.Date.context_today(self)
                provider._update(date_from, date_to, newest_only=newest_only)
```

This way, I think the behavior should become like how you describe (except for the "and set `next_run` on the last day that fetches data" part, which I think you meant `last_successful_run` perhaps).  Let us know if this makes sense.

@kanda999 Can you go ahead and check if above suggestion works.

2022-12-28 10:39 UTC, pedrobaeza commented
Well, the goal is to not lose a day rate if something goes bad on the daily cron. The previous case with ECB was that they publish the rates at 17:00, so if you run the cron before that date, internal data was changed and no more possibility to get the rate for that date.

If the algorithm should take `last_successful_run` or `next_run`, I don't know right now. I wonder also why 2 variables are needed at the end. I would say that fetching from `last_successful_run` to today, and setting `last_successful_run` on the last fetched date would be enough.

2022-12-29 06:23 UTC, kanda999 commented
> If the algorithm should take `last_successful_run` or `next_run`, I don't know right now. I wonder also why 2 variables are needed at the end. I would say that fetching from `last_successful_run` to today, and setting `last_successful_run` on the last fetched date would be enough.

Users do not necessarily want to get data every day..  User can set interval_type and interval_number.  next_run have the date until the next time get data, so next_run is needed for the variable.

I updated @yostashiro suggestion.  It follows when interval_type is days and interval_number is 1.

2022-12-29 09:45 UTC, pedrobaeza approved these changes
Just a thought: do you really think someone is fetching rates by other interval than day?

2022-12-29 17:12 UTC, yostashiro requested changes

2022-12-29 17:12 UTC, yostashiro commented on currency_rate_update/models/res_currency_rate_provider.py
>                  provider._schedule_last_successful_run()
```suggestion
                provider._schedule_last_successful_run(newest_date)
```

2022-12-29 17:12 UTC, yostashiro commented on currency_rate_update/models/res_currency_rate_provider.py
>          self.last_successful_run = self.next_run
```suggestion
    def _schedule_last_successful_run(self, newest_date):
        self.last_successful_run = newest_date
```

2022-12-29 17:12 UTC, yostashiro commented on currency_rate_update/tests/test_currency_rate_update.py
> +        self.assertEqual(self.ecb_provider.next_run, self.today)
I suppose we cannot rely on this test and we should remove this.  In fact, we should not use/update `next_run` at all if the provider is configured for daily updates.

2022-12-29 17:22 UTC, yostashiro commented
> Just a thought: do you really think someone is fetching rates by other interval than day?

We are in no position to be able to judge this.  We have internal practice of setting rates monthly in our company but are not using this module.

2022-12-30 08:45 UTC, yostashiro requested changes

2022-12-30 08:45 UTC, yostashiro commented on currency_rate_update/models/res_currency_rate_provider.py
> +        # If you set daily update, fetch to today date.
```suggestion
        # next_run is not used when daily is true, but we are updating the value anyway.
```

2022-12-30 08:45 UTC, yostashiro commented on currency_rate_update/models/res_currency_rate_provider.py
> +        # When you set daily, you should get data up to today.
```suggestion
        # When daily is true, the provider should always be picked for scheduled update.
```

2022-12-30 08:45 UTC, yostashiro commented on currency_rate_update/models/res_currency_rate_provider.py
> +    daily = fields.Boolean(compute="_compute_daily_provider", store=True)
```suggestion
    daily = fields.Boolean(compute="_compute_daily", store=True)
```

2022-12-30 08:45 UTC, yostashiro commented on currency_rate_update/models/res_currency_rate_provider.py
> +    def _compute_daily_provider(self):
```suggestion
    def _compute_daily(self):
```

2022-12-30 08:45 UTC, yostashiro commented on currency_rate_update/tests/test_currency_rate_update.py
> +        # Because defferent URL is used in ECB.
```suggestion
        # Setting last_successful_run a date more than 90 days prior to the freeze_time date,
        # to make sure that the rates are taken from '/eurofxref-hist.xml'.
```

2022-12-30 08:45 UTC, yostashiro commented on currency_rate_update/tests/test_currency_rate_update.py
> +        self.ecb_provider.next_run = date(2022, 4, 19)
```suggestion
```

2022-12-30 08:45 UTC, yostashiro commented on currency_rate_update/views/res_currency_rate_provider.xml
> +                <field name="daily" invisible="1" />
```suggestion
                <field name="daily" invisible="1" />
                <field name="next_run" attrs="{'invisible': [('daily', '=', True)]}"/>
```

2022-12-30 08:45 UTC, yostashiro commented on currency_rate_update/views/res_currency_rate_provider.xml
> +                            <field name="daily" invisible="1" />
```suggestion
                            <field name="daily" invisible="1" />
                            <field name="next_run" attrs="{'invisible': [('daily', '=', True)]}" />
```

2022-12-30 09:13 UTC, yostashiro commented
@kanda999 Please squash commits and add proper commit message.

2022-12-30 12:18 UTC, yostashiro approved these changes
LGTM. 👍

2022-12-30 12:21 UTC, yostashiro commented
@pedrobaeza Can you please review this again as the code has been updated since your approval?

2022-12-30 14:59 UTC, dreispt commented
/ocabot merge minor

2022-12-30 15:03 UTC, pedrobaeza commented
OK, in a quick glance seems correct. Tell us when you apply it to your instances to backport it.

2022-12-30 15:07 UTC, merged