[15.0][ADD] currency_rate_update_xe: new module
OCA/currency pull request #169
Opened 2023-04-11 08:26 UTC by ernestotejeda

Cc @Tecnativa TT42478

This is a new module with the same functionality as the existing one in an older version.

ping @pedrobaeza @chienandalu

2023-04-11 08:52 UTC, chienandalu approved these changes
Works great :+1:

2023-04-11 19:48 UTC, pedrobaeza requested changes
Please add the logo: https://www.xe.com/themes/xe/images/apps/bots/xe-logo.png as icon

2023-04-11 19:48 UTC, pedrobaeza commented on currency_rate_update_xe/README.rst
> +This module provides adds `XE.com <https://xe.com/>`_. currency exchange rates
```suggestion
This module adds `XE.com <https://xe.com/>`_. currency exchange rates
```

2023-04-11 19:48 UTC, pedrobaeza commented on currency_rate_update_xe/README.rst
> +Now you can choose the 'XE.com' service when configuring currency rates providers.
Please put full instructions on how to get there.

2023-04-11 19:48 UTC, pedrobaeza commented on currency_rate_update_xe/README.rst
> +provider.
Put a disclaimer saying that the rates are fetched scrapping the corresponding web page. Being a public page, it's legal according sentences like https://seointel.com/news/the-court-determines-that-data-scraping-is-legal-on-linkedin/

2023-04-11 19:48 UTC, pedrobaeza commented on currency_rate_update_xe/models/res_currency_rate_provider_XE.py
> +        return self.env["res.currency"].search([]).mapped("name")
Are you sure that all the currencies are supported?

2023-04-13 18:20 UTC, pedrobaeza approved these changes
/ocabot merge nobump

2023-04-13 18:20 UTC, pedrobaeza commented on currency_rate_update_xe/models/res_currency_rate_provider_XE.py
> +        # List of currencies obrained from: https://www.xe.com/currency/
```suggestion
        # List of currencies obtained from: https://www.xe.com/currency/
```

2023-04-13 18:27 UTC, merged