[IMP] Make the method get_exchange_rate overridable to adapt some special banks
OCA/currency pull request #38
Opened 2018-12-17 12:28 UTC by novawish

Original issue from module [currency_rate_update_vn_VCB](https://github.com/OCA/l10n-vietnam/pull/8):

[VCB service](http://www.vietcombank.com.vn/ExchangeRates/ExrateXML.aspx) already provided the rates as inverted compared with main currency (VND).

So when using this module along with `currency_rate_inverted`, it does not work properly with the inverted rate (inverts the rates that were already inverted).

By providing the overridable mechanism, we'll allow people to handle some specific cases for specific bank services easier.

2018-12-17 12:46 UTC, pedrobaeza requested changes
Please include in the method all the code for getting the rate (the search and so on), not only the part you are interested in.

2018-12-17 16:55 UTC, novawish commented
Sorry I'm not really sure what you mean.
I split that part to a new method not because i like it, but it would be easier for another module to override it thus calling the super and only change the necessary code that affects the exchange rate.
Can you explain more details about how do we make an override-able method?

2018-12-17 17:03 UTC, pedrobaeza commented
I'm saying to extract from line 179 to 190.

2018-12-18 03:04 UTC, novawish commented
@pedrobaeza Done, can you please check?

2018-12-18 05:11 UTC, novawish commented
BTW, i'm not sure travis's failure is related to this change (the automatic tests failed on module `account_fx_spot`)
![image](https://user-images.githubusercontent.com/31387997/50133372-e1b01a80-02bd-11e9-8104-6d66725cb2ed.png)

2018-12-18 08:51 UTC, pedrobaeza commented
You have a flake8 error: `currency_rate_update/models/currency_rate_update.py:161:9: F841 local variable 'rate_obj' is assigned to but never used`, but the rest is a change upstream. @jbeficent were you the one that added `account_fx_spot` module?

2019-02-11 07:34 UTC, Syentystech1 commented
@jbeficent could you please answer @pedrobaeza ? We are a bit blocked, waiting for that PR.  Thanks :)

2019-02-12 04:36 UTC, novawish commented
@pedrobaeza I've done the modifications following your suggestion. However after thinking for a long time i think it's really not convenient for other modules to override the function in order to interfere the method generating the rates (for example with current customization i had to override the whole function and could not call super). Can you help me on this?

Thanks very much.

2019-02-14 13:29 UTC, pedrobaeza commented
@novawish Indeed it seems a bit weird that you need to override this basic method, but I didn't want to judge.

2019-02-18 20:09 UTC, alexey-pelykh commented
In #42 for v12 there has been a refactor that would allow banks to provide both rates or just inverted or just direct, if I got this issue correctly

2019-02-19 18:44 UTC, novawish commented
@alexey-pelykh You got it correctly.
However what i wonder is if any chances that the solution would be backported to version 11?
Thanks so much for your comment.

2019-02-19 18:49 UTC, alexey-pelykh commented
@novawish well, "as-is" very unlikely, since it would mean that all already-ported currency providers available would have to be refactored as well. For v12 it's easier since nothing is yet ported. Yet it would be possible to grab same approach from #42 and to make less heavy change in the module itself. Idea is that if `rate = res[curr.name]` is scalar value, treat is as before, yet if it's a dictionary with `inverted` key and currency is inverted - don't do the inversion magic. I believe that's the only way to get at least something backported.

2019-05-24 03:01 UTC, novawish commented
@alexey-pelykh @pedrobaeza I updated the method to generate the rates, please help me to check.

BTW, travis failed apparently because of module `account_fx_spot`, so i don't know how i can fix it

2019-06-21 00:46 UTC, novawish commented
@alexey-pelykh @pedrobaeza Travis and runbot are green now, it would be great if you let some reviews.

2019-06-21 03:22 UTC, alexey-pelykh commented
@novawish you may take a look on how this module was reworked for v12, there are extra cases handled of cross-currency inversions.

2019-06-21 03:28 UTC, alexey-pelykh requested changes
Please cover your change with tests

2019-06-25 06:36 UTC, novawish commented
@alexey-pelykh It's all green now :)

2019-06-25 07:13 UTC, alexey-pelykh approved these changes
Code LGTM, yet this would need manual testing "just to be sure" - which I haven't done

2019-06-25 17:22 UTC, novawish commented
@alexey-pelykh Of course it was manually tested on my local. However AFAIK there's only one service that could take advantage from this change is [currency_rate_update_vn_VCB](https://github.com/OCA/l10n-vietnam/pull/8) (is also the reason why i made this PR as mentioned earlier from the beginning).

So to say, if this PR is merged, we will proceed to adapt the module above to use this new implementation.

Thanks very much for all of your help, you did brighten me a lot :)

2019-06-25 17:49 UTC, novawish commented
@pedrobaeza May I get your kind review on this? Thank you.

2019-06-26 11:23 UTC, pedrobaeza approved these changes

2019-06-26 11:23 UTC, pedrobaeza commented
/ocabot merge

I haven't tested myself, but trusting on your good knowledge :smiley:

2019-06-26 11:41 UTC, pedrobaeza commented
/ocabot merge

2019-06-26 13:30 UTC, merged