[12.0][MIG] currency_rate_inverted
OCA/currency pull request #41
Opened 2019-02-13 06:45 UTC by alexey-pelykh

2019-02-13 06:45 UTC, alexey-pelykh commented
@jbeficent @aheficent please review, if you don't mind

2019-04-08 08:44 UTC, alexey-pelykh commented
@jbeficent @aheficent is there a chance to obtain your reviews? :)

2019-04-08 16:52 UTC, jcdrubay approved these changes

2019-04-16 15:36 UTC, tbaden requested changes
thanks for your work. just a minor detail (see below).

 runbot is rebuilding right now. will test this as well when finished.

2019-04-16 15:36 UTC, tbaden commented on currency_rate_inverted/__manifest__.py
> +    'test': [],
if the tag is empty just delete it.

2019-04-16 15:39 UTC, alexey-pelykh commented on currency_rate_inverted/__manifest__.py
> +    'test': [],
Fixed

2019-04-16 15:58 UTC, tbaden approved these changes
code review: lgtm now

tested in rundeck as well.
inverted currency1 inverted currency2
False False
True False
False True
True True

all combinations calculated correctly

2019-05-21 12:35 UTC, novawish commented
> code review: lgtm now
> 
> tested in rundeck as well.
> inverted currency1 inverted currency2
> False False
> True False
> False True
> True True
> 
> all combinations calculated correctly

Did you try these combinations for 2 currencies that are different from main currency (company's currency)?

Because I just used this module for my project that have: USD, EUR (both are inverted), and VND (main currency).

The rates of USD and EUR compared to VND were correct. However when I do the conversion from EUR to USD apparently the rate is wrongly inverted as the picture below
![image](https://user-images.githubusercontent.com/31387997/58096192-b760e100-7bfe-11e9-8247-2c904dead3a7.png)

There's no way that EUR is larger than USD right?
The reason why both EUR and USD are inverted because VND is a very small currency (1 USD ~ 23000 VND).

In general, i think this module does not handle the case above.
I'm not sure that I did something wrong in the configuration, could somebody help me about that?

2019-05-21 13:09 UTC, jcdrubay commented
Would this do the trick ?

```python


    @api.model
    def _get_conversion_rate(self, from_currency, to_currency, company, date):
        res = super(ResCurrency, self)._get_conversion_rate(from_currency,
                                                            to_currency)

        if (not from_currency.rate_inverted and not to_currency.rate_inverted):
            # Everything normal
            pass
        elif (from_currency.rate_inverted and to_currency.rate_inverted):
            res = 1 / res
        else:
            currency_rates = (from_currency + to_currency)._get_rates(
                company, date)

            if from_currency.rate_inverted:
                rate_from = 1 / currency_rates.get(from_currency.id)
            else:
                rate_from = currency_rates.get(from_currency.id)

            if to_currency.rate_inverted:
                rate_to = 1 / currency_rates.get(to_currency.id)
            else:
                rate_to = currency_rates.get(to_currency.id)

            res = rate_to / rate_from

        return res

```

2019-05-21 16:23 UTC, alexey-pelykh commented
@novawish please check updated version

2019-05-21 22:36 UTC, novawish approved these changes
Looks good! Thanks for taking care of my comment.

2019-05-23 10:42 UTC, alexey-pelykh commented
@pedrobaeza ?

2019-05-23 11:11 UTC, pedrobaeza commented
Blindly merging due to the approvals of other contributors.

2019-05-23 11:11 UTC, merged

2019-05-23 11:36 UTC, novawish commented
@alexey-pelykh Since the implementation before did not handle those cases, can we do back-porting for the previous versions?