[12.0][ADD] currency_rate_update_oxr: OpenExchangeRates.org provider
OCA/currency pull request #51
Opened 2019-05-01 03:18 UTC by alexey-pelykh

This module provides adds OpenExchangeRates.org currency exchange rates provider.

2019-05-01 11:06 UTC, pedrobaeza commented
Please check Travis

2019-05-01 12:09 UTC, alexey-pelykh commented
@pedrobaeza fixed

2019-05-01 13:10 UTC, pedrobaeza approved these changes

2019-05-01 22:40 UTC, jcdrubay requested changes
LGTM, only small updates to do for repleacement of XE by OpenExchangeRates.org

2019-05-01 22:40 UTC, jcdrubay commented on currency_rate_update_oxr/readme/DESCRIPTION.rst
> +This module provides adds `OpenExchangeRates.org <https://openexchangerates.org/>`_
Remove `provides`

2019-05-01 22:40 UTC, jcdrubay commented on currency_rate_update_oxr/README.rst
> +Currency Rate Update: XE.com
Should be OpenExchangeRates.org

2019-05-01 22:40 UTC, jcdrubay commented on currency_rate_update_oxr/README.rst
> +To configure XE.com currency rates provider credentials:
OpenExchangeRates.org

2019-05-01 22:40 UTC, jcdrubay commented on currency_rate_update_oxr/README.rst
> +# Fill application credentials in *Currencies > XE.com Provider* section
OpenExchangeRates.org

2019-05-02 07:17 UTC, alexey-pelykh commented on currency_rate_update_oxr/readme/DESCRIPTION.rst
> +This module provides adds `OpenExchangeRates.org <https://openexchangerates.org/>`_
Fixed, thanks!

2019-05-02 07:17 UTC, alexey-pelykh commented on currency_rate_update_oxr/README.rst
> +Currency Rate Update: XE.com
Regenerated

2019-05-02 07:17 UTC, alexey-pelykh commented on currency_rate_update_oxr/README.rst
> +# Fill application credentials in *Currencies > XE.com Provider* section
Regeneratd

2019-05-02 15:16 UTC, Syentystech1 approved these changes

2019-05-02 15:21 UTC, jcdrubay approved these changes

2019-05-09 15:59 UTC, merged