[11.0][add][currency_rate_update_cmc]
OCA/currency pull request #7
Opened 2018-03-20 12:56 UTC by jbeficent

Currency Rate Update Coin Market Cap
====================================

This module introduces the ability to download the exchange rates associated to
crypto currencies from https://coinmarketcap.com

Configuration
=============

To convert amounts from one currency to another using the inverse method,
you have to go to 'Accounting / Configuration / Miscellaneous / Currencies'.
Then select the foreign currency that you wish to maintain inversion for
and set the flag 'Inverted exchange rate'.

Installation
============

This module depends on *currency_rate_update*, found
in https://github.com/OCA/currency.

It is advisable to install the module *currency_rate_inverted*, found in
https://github.com/OCA/currency, to store the exchange rate in inverted
format and avoid rounding issues for crypto currencies that are very large
compared to the main company currency.

Configuration
=============

* Go to *Invoicing / Configuration / Accounting / Currencies* and create the
  required crypto currencies. See https://coinmarketcap.com/coins/views/all
  for supported currencies.

* Go to *Invoicing / Configuration / Accounting / Currency Rate Update* and
  create a new Update Service indicating Webservice to use = 'Coin Market Cap'.

2018-03-20 13:50 UTC, jbeficent commented
@lreficent @rossigee can you review?

2018-03-20 14:37 UTC, LoisRForgeFlow approved these changes
Tested on runbot LGTM :+1:

2018-03-20 14:37 UTC, lreficent commented on currency_rate_update_cmc/README.rst
> +you have to go to 'Accounting / Configuration / Miscellaneous / Currencies'.
`Accounting / Configuration / Accounting / Currencies`

2018-04-07 19:44 UTC, jbeficent commented
@elicoidal this is closely related with account_cryptocurrency. Would really appreciate your review.

2018-04-10 00:28 UTC, elicoidal requested changes
small details

2018-04-10 00:28 UTC, elicoidal commented on currency_rate_update_cmc/README.rst
> +To convert amounts from one currency to another using the inverse method,
You might want to use enumerated list

2018-04-10 00:28 UTC, elicoidal commented on currency_rate_update_cmc/services/update_service_CMC.py
> +        """implementation of abstract method of Curreny_getter_interface"""
currency

2018-04-10 00:28 UTC, elicoidal commented on currency_rate_update_cmc/services/update_service_CMC.py
> +                        1.0 / float(val[main_currency_attr])
Are certain it will never be 0?

2018-04-10 00:28 UTC, elicoidal commented on currency_rate_update_cmc/services/update_service_CMC.py
> +        url = 'https://api.coinmarketcap.com/v1/ticker/?convert=' + \
Can you make it a constant?

2018-04-11 09:19 UTC, JordiBForgeFlow commented
Thanks @elicoidal I have attended your comments.

2018-04-11 10:01 UTC, elicoidal approved these changes
LGTM

2018-04-11 10:21 UTC, merged